/*
 * JTWAbout.java
 *
 * Created on Jan 16, 2009, 2:45:05 AM
 */

package org.jtw.ui.gui;

/**
 * JTW About window.
 * @author Stas SUHKOV (stas@nerd.ro)
 */
public class JTWAbout extends javax.swing.JFrame {

    /** Creates new form JTWAbout */
    public JTWAbout() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedAboutText = new javax.swing.JTabbedPane();
        jTextAbout = new javax.swing.JTextArea();
        jTextCredits = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JTW - About");

        jTabbedAboutText.setName("About"); // NOI18N

        jTextAbout.setColumns(20);
        jTextAbout.setEditable(false);
        jTextAbout.setRows(5);
        jTextAbout.setText("JTW is a Twitter client, build above jtwitterlib.\nVersion 1.0 beta.\n\nJTW is written in Java. And was born as a project \nfor my Java CS labs driven by prof. Marius JOLDOS\nat Technical University of Cluj-Napoca.\nhttp://cs.utcluj.ro");
        jTextAbout.setFocusable(false);
        jTabbedAboutText.addTab("About JTW", jTextAbout);

        jTextCredits.setColumns(20);
        jTextCredits.setEditable(false);
        jTextCredits.setRows(5);
        jTextCredits.setText("jtwitterlib (c) 2007 by Lukasz Grzegorz Maciak\nhttp://jtwitt.googlecode.com/\n\nJTW (c) 2009 by Stas SUSHKOV\nhttp://stas.nerd.ro/\nhttp://nerd.googlecode.com/\nBoth jtwitterlib and JTW are released under GPL.");
        jTextCredits.setFocusable(false);
        jTabbedAboutText.addTab("Credits", jTextCredits);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedAboutText, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedAboutText, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedAboutText.getAccessibleContext().setAccessibleName("About");
        jTabbedAboutText.getAccessibleContext().setAccessibleDescription("About JTW");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Main function.
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTWAbout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedAboutText;
    private javax.swing.JTextArea jTextAbout;
    private javax.swing.JTextArea jTextCredits;
    // End of variables declaration//GEN-END:variables

}
