/*
 * JTWConfigDialog.java
 *
 * Created on Jan 16, 2009, 3:58:24 AM
 */

package org.jtw.ui.gui;

import org.jtw.ui.JTwittConfig;


/**
 * JTW Config Dialog window.
 * Dialog loads and saves user specified username and password.
 * @author Stas SUHKOV (stas@nerd.ro)
 */
public class JTWConfigDialog extends javax.swing.JDialog {

    /** Creates new form JTWConfigDialog */
    public JTWConfigDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Username = new javax.swing.JLabel();
        JTwittConfig conf = new JTwittConfig();
        conf.loadConfig();
        JTWConfUsername = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        JTWConfPassword = new javax.swing.JPasswordField();
        jTextArea1 = new javax.swing.JTextArea();
        JTWConfSave = new javax.swing.JButton();
        JTWConfCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JTWConfig");

        Username.setText("Username:");

        JTWConfUsername.setText(conf.getUsername());

        Password.setText("Password:");

        JTWConfPassword.setText(conf.getPassword());

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText("These details will be stored in you home folder in a file\nnamed \".jtwitt\". (~/.jtwitt)");
        jTextArea1.setEnabled(false);
        jTextArea1.setFocusable(false);

        JTWConfSave.setText("Save");
        JTWConfSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTWConfSaveActionPerformed(evt);
            }
        });

        JTWConfCancel.setText("Cancel");
        JTWConfCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTWConfCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username)
                            .addComponent(Password))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTWConfPassword)
                            .addComponent(JTWConfUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JTWConfSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTWConfCancel)))
                .addGap(214, 214, 214))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTextArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username)
                    .addComponent(JTWConfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Password)
                    .addComponent(JTWConfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTWConfSave)
                    .addComponent(JTWConfCancel))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action for Save button.
     * Gets user preferences and creates or saves the .jtwitt file with these.
     * Then closes the dialog.
     * @param evt
     */
    private void JTWConfSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTWConfSaveActionPerformed
        // TODO add your handling code here:
        JTwittConfig conf = new JTwittConfig();
        conf.setUsername(this.JTWConfUsername.getText());
        conf.setPassword(this.JTWConfPassword.getText());
        conf.createNewConfig();
        this.dispose();
}//GEN-LAST:event_JTWConfSaveActionPerformed

    /**
     * Action for Cancel button.
     * Ignores any changes and closes dialog.
     * @param evt
     */
    private void JTWConfCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTWConfCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JTWConfCancelActionPerformed

    /**
    * Main function for our Config Dialog.
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JTWConfigDialog dialog = new JTWConfigDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JTWConfCancel;
    private javax.swing.JPasswordField JTWConfPassword;
    private javax.swing.JButton JTWConfSave;
    private javax.swing.JTextField JTWConfUsername;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Username;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
