/*
 * JTWGui.java
 *
 * Created on Jan 16, 2009, 3:43:28 AM
 */

package org.jtw.ui.gui;

import java.io.IOException;
import java.io.InputStream;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.ParserConfigurationException;
import org.jtw.ui.JTwittConfig;
import org.jtwitterlib.net.TwitterConnection;
import org.jtwitterlib.xml.TwitterXMLParser;
import org.xml.sax.SAXException;

/**
 * Main JTW Window class.
 * It contains the main frame with drop down menus, updates status in one tab
 * and update form in another tab.
 * @author Stas SUHKOV (stas@nerd.ro)
 */
public class JTWGui extends javax.swing.JFrame {

    /** Creates new form JTWGui */
    public JTWGui() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTWGuiOperations = new javax.swing.JTabbedPane();
        JTWGuiUpdates = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTWUpdatesFlow = new javax.swing.JTextArea();
        JTWGuiNewStatus = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTWGuiNewUpdateMessage = new javax.swing.JTextArea();
        JTWGuiUpdateStatusButton = new javax.swing.JToggleButton();
        JTWGuiNewUpdateStatus = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        connectMenu = new javax.swing.JMenuItem();
        configMenu = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JTW");
        setName("JTWGui"); // NOI18N

        JTWGuiUpdates.setBorder(javax.swing.BorderFactory.createTitledBorder("Your Friends Updates"));

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusable(false);

        JTWUpdatesFlow.setColumns(20);
        JTWUpdatesFlow.setEditable(false);
        JTWUpdatesFlow.setLineWrap(true);
        JTWUpdatesFlow.setRows(5);
        JTWUpdatesFlow.setTabSize(4);
        JTWUpdatesFlow.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(JTWUpdatesFlow);

        javax.swing.GroupLayout JTWGuiUpdatesLayout = new javax.swing.GroupLayout(JTWGuiUpdates);
        JTWGuiUpdates.setLayout(JTWGuiUpdatesLayout);
        JTWGuiUpdatesLayout.setHorizontalGroup(
            JTWGuiUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTWGuiUpdatesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );
        JTWGuiUpdatesLayout.setVerticalGroup(
            JTWGuiUpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTWGuiUpdatesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );

        JTWGuiOperations.addTab("Latest Updates", JTWGuiUpdates);

        JTWGuiNewStatus.setBorder(javax.swing.BorderFactory.createTitledBorder("What are you doing right now?"));

        JTWGuiNewUpdateMessage.setColumns(20);
        JTWGuiNewUpdateMessage.setLineWrap(true);
        JTWGuiNewUpdateMessage.setRows(5);
        jScrollPane2.setViewportView(JTWGuiNewUpdateMessage);

        JTWGuiUpdateStatusButton.setText("Twitter it!");
        JTWGuiUpdateStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTWGuiUpdateStatusButtonActionPerformed(evt);
            }
        });

        JTWGuiNewUpdateStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout JTWGuiNewStatusLayout = new javax.swing.GroupLayout(JTWGuiNewStatus);
        JTWGuiNewStatus.setLayout(JTWGuiNewStatusLayout);
        JTWGuiNewStatusLayout.setHorizontalGroup(
            JTWGuiNewStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTWGuiNewStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JTWGuiNewStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTWGuiUpdateStatusButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(JTWGuiNewUpdateStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        JTWGuiNewStatusLayout.setVerticalGroup(
            JTWGuiNewStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTWGuiNewStatusLayout.createSequentialGroup()
                .addComponent(JTWGuiNewUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTWGuiUpdateStatusButton)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        JTWGuiOperations.addTab("Update your status", JTWGuiNewStatus);

        fileMenu.setText("JTW");

        connectMenu.setText("Connect");
        connectMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectMenuActionPerformed(evt);
            }
        });
        fileMenu.add(connectMenu);

        configMenu.setText("Preferences");
        configMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configMenuActionPerformed(evt);
            }
        });
        fileMenu.add(configMenu);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTWGuiOperations, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTWGuiOperations, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action for Exit menu item.
     * Closes imediately the JTW Main Window.
     * @param evt
     */
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /**
     * Action for About item.
     * Opens a new window which contains the credits and some application description.
     * See JTWAbout class.
     * @param evt
     */
    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        new JTWAbout().setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    /**
     * Action for Config item.
     * Opens a new dialog which offers possibilty to specify a username and a
     * password in order to connect to the Twitter API.
     * See JTWConfigDialog class.
     * @param evt
     */
    private void configMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configMenuActionPerformed
        // TODO add your handling code here:
        new JTWConfigDialog(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_configMenuActionPerformed

    /**
     * Action for Connect item.
     * Action calls connectPerformed hook with the right textArea inside where to
     * put all the data.
     * @param evt
     */
    private void connectMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectMenuActionPerformed
        // TODO add your handling code here:
        connectPerformed(JTWUpdatesFlow);
    }//GEN-LAST:event_connectMenuActionPerformed

    /**
     * Action for Update Status button.
     * Method gets the text from JTWGuiNewUpdateMessage textArea and sens it to
     * Twitter API.
     * It also updates the JTWGuiNewUpdateStatus Jlabel which is invisible from start.
     * It uses directly jtwitterlib, so have a look at TwitterConnection class.
     * @param evt
     * To Do: Set a counter to JTWGuiNewUpdateStatus JLabel and JTWGuiNewUpdateMessage
     * to clear their texts.
     */
    private void JTWGuiUpdateStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTWGuiUpdateStatusButtonActionPerformed
        try {
            // TODO add your handling code here:
            JTwittConfig conf = new JTwittConfig();
            TwitterConnection twitter = new TwitterConnection();
            conf.loadConfig();
            TwitterConnection.sendTwitterUpdate(conf.getUsername(), conf.getPassword(), JTWGuiNewUpdateMessage.getText());
        } catch (IOException ex) {
            Logger.getLogger(JTWGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        JTWGuiNewUpdateStatus.setText("Status Updated!");
    }//GEN-LAST:event_JTWGuiUpdateStatusButtonActionPerformed

    /**
     * Hook for connect action.
     * Method loads preferences from config file and connects to Twitter API.
     * It gets the latest statuses of the user friends and fills the JTWUpdatesFlow
     * textArea with the results.
     * It uses directly jtwitterlib, so have a look at TwitterConnection class.
     * @param textArea 
     * To Do: Format the flowing data with swing elements.
     */
    private void connectPerformed(javax.swing.JTextArea textArea) {
        JTwittConfig conf = new JTwittConfig();
        conf.loadConfig();
        try {
            InputStream s = TwitterConnection.getFriendsTimelineStream(conf.getUsername(), conf.getPassword());

            TwitterXMLParser p = new TwitterXMLParser();

            p.parse(s);
            
            for (int i = 0; i < p.getNumberOfItems(); i++) {
                try {
                    textArea.append(p.getItemAt(i) + "\n\n");
                } catch (ParseException parseException) {
                }
            }
        
        } catch (IOException iOException) {
        } catch (SAXException sAXException) {
        } catch (ParserConfigurationException parserConfigurationException) {
        }
    }

    /**
    * Main JTW Gui method.
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTWGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JTWGuiNewStatus;
    private javax.swing.JTextArea JTWGuiNewUpdateMessage;
    private javax.swing.JLabel JTWGuiNewUpdateStatus;
    private javax.swing.JTabbedPane JTWGuiOperations;
    private javax.swing.JToggleButton JTWGuiUpdateStatusButton;
    private javax.swing.JPanel JTWGuiUpdates;
    private javax.swing.JTextArea JTWUpdatesFlow;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem configMenu;
    private javax.swing.JMenuItem connectMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
